import type { GiftItem } from './types';

const now = new Date().toISOString();

export const seedGifts: GiftItem[] = [
  {
    id: 'kitchen-pan-set',
    title: 'Ceramic Nonstick Cookware Set',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80',
    store: 'Amazon',
    storeUrl: 'https://www.amazon.com/s?k=ceramic+nonstick+cookware+set',
    price: 119,
    description: 'Everyday pots and pans for weeknight dinners and hosting friends.',
    priority: 'Must Have',
    category: 'Kitchen',
    status: 'Available',
    reservedByName: null,
    reservedByEmail: null,
    purchasedByName: null,
    purchasedByEmail: null,
    thankYouSent: false,
    notes: '',
    createdAt: now,
    updatedAt: now
  },
  {
    id: 'living-room-lamp',
    title: 'Warm Floor Lamp',
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
    store: 'Wayfair',
    storeUrl: 'https://www.wayfair.com/keyword.php?keyword=warm+floor+lamp',
    price: 86,
    description: 'Soft lighting for the living room reading corner.',
    priority: 'Nice to Have',
    category: 'Living Room',
    status: 'Reserved',
    reservedByName: 'Aunt Lisa',
    reservedByEmail: null,
    purchasedByName: null,
    purchasedByEmail: null,
    thankYouSent: false,
    notes: '',
    createdAt: now,
    updatedAt: now
  },
  {
    id: 'bathroom-towel-set',
    title: 'Hotel Cotton Towel Bundle',
    imageUrl: 'https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?auto=format&fit=crop&w=900&q=80',
    store: 'Walmart',
    storeUrl: 'https://www.walmart.com/search?q=cotton+towel+bundle',
    price: 48,
    description: 'Neutral bath towels and hand towels for guests.',
    priority: 'Must Have',
    category: 'Bathroom',
    status: 'Available',
    reservedByName: null,
    reservedByEmail: null,
    purchasedByName: null,
    purchasedByEmail: null,
    thankYouSent: false,
    notes: '',
    createdAt: now,
    updatedAt: now
  },
  {
    id: 'smart-home-speaker',
    title: 'Smart Speaker',
    imageUrl: 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?auto=format&fit=crop&w=900&q=80',
    store: 'Amazon',
    storeUrl: 'https://www.amazon.com/s?k=smart+speaker',
    price: 55,
    description: 'Compact speaker for music, timers, and smart home controls.',
    priority: 'Optional',
    category: 'Smart Home',
    status: 'Purchased',
    reservedByName: null,
    reservedByEmail: null,
    purchasedByName: 'Morgan',
    purchasedByEmail: null,
    thankYouSent: true,
    notes: '',
    createdAt: now,
    updatedAt: now
  },
  {
    id: 'garden-tool-kit',
    title: 'Starter Garden Tool Kit',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=900&q=80',
    store: 'Walmart',
    storeUrl: 'https://www.walmart.com/search?q=garden+tool+kit',
    price: 38,
    description: 'Hand tools for planting herbs and keeping the yard tidy.',
    priority: 'Nice to Have',
    category: 'Outdoor',
    status: 'Available',
    reservedByName: null,
    reservedByEmail: null,
    purchasedByName: null,
    purchasedByEmail: null,
    thankYouSent: false,
    notes: '',
    createdAt: now,
    updatedAt: now
  },
  {
    id: 'gift-card',
    title: 'Home Improvement Gift Card',
    imageUrl: 'https://images.unsplash.com/photo-1561715276-a2d087060f1d?auto=format&fit=crop&w=900&q=80',
    store: 'Any Store',
    storeUrl: 'https://www.walmart.com/cp/gift-cards/96894',
    price: null,
    description: 'A flexible option for paint, hardware, plants, or a future project.',
    priority: 'Optional',
    category: 'Gift Card',
    status: 'Available',
    reservedByName: null,
    reservedByEmail: null,
    purchasedByName: null,
    purchasedByEmail: null,
    thankYouSent: false,
    notes: 'Any amount is appreciated.',
    createdAt: now,
    updatedAt: now
  }
];
